environment:
  
  stage:
  
    grpc_server_addr: profile:9402
  
    log_level: error
  
  
  development:
  
    grpc_server_addr: localhost:9402
  
    log_level: debug
  
  
  testing:
    
    grpc_server_addr: localhost:9402
    
    log_level: debug
    
    database_url: ${DB_TEST_URL}
