on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASS }}
          POSTGRES_DB: ${{ secrets.DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
              go-mod-${{ runner.os }}-

      - name: Install dependencies
        run: go mod tidy

      - name: Install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/migrate

      - name: Run database migrations
        run: |
          migrate -path ./migrations -database ${{ secrets.DB_URL }} up

      - name: Run tests
        env:
          DB_TEST_URL: ${{ secrets.DB_URL }}
        run: go test ./...
        
      - name: Run build
        run: go build -v -a ./...
